# This workflow will update release vertion in `setup` files whenever a release is published.

name: Update versino to latest

on:
  release:
    types: [published, deleted]

permissions:
  contents: write
  packages: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: update latest version in setup scripts
        env:
          GITHUB_ACTION: ${{ github.event.action }}
          TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: scripts/update-release-version.sh
